# SITE SETUP
# Guide: https://wowchemy.com/docs/getting-started/
# Documentation: https://wowchemy.com/docs/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance

theme: 1950s
day_night: true
theme_day: rose
theme_night: coffee
font: classic
font_size: m

# SEO

site_type: Person
local_business_type: ''
org_name: ''
description: ''
twitter: ''

# Contact (edit or remove options as required)

email: sahidyk@gmail.com, sahid@uny.ac.id
phone: +62 274 550846
address:
  street: Jurusan Pendidikan Matematika FMIPA UNY
  city: Yogyakarta
  region: DIY
  postcode: '55281'
  country: Indonesia
  country_code: ID
coordinates:
  latitude: '-7.77533'
  longitude: '110.38501'
directions: Kompleks Gedung Lab FMIPA Lt 3
office_hours:
  - 'Senin s.d. Jum`at'
  - '07:30 s.d. 16:00'
#appointment_url: 'https://calendly.com'
#contact_links:
#  - icon: twitter
#    icon_pack: fab
#    name: DM Me
#    link: 'https://twitter.com/Twitter'
#  - icon: skype
#    icon_pack: fab
#    name: Skype Me
#    link: 'skype:echo123?call'
#  - icon: keybase
#    icon_pack: fab
#    name: Chat on Keybase
#    link: 'https://keybase.io/'
#  - icon: comments
#    icon_pack: fas
#    name: Forum diskusi
#    link: 'https://discourse.gohugo.io'

# Site header

main_menu:
  enable: true
  align: l
  show_logo: true
  show_language: false
  show_day_night: true
  show_search: true
  highlight_active_link: true

# Localization

date_format: '2 Jan, 2006'
time_format: '15:04'
address_format: en-us

# Site features

highlight: true
highlight_languages:
  - r
  - latex
  - python
math: 
 enable: true
diagram: true
privacy_pack: true
edit_page:
  repo_url: ''
  content_dir: ''
  repo_branch: main
  editable:
    page: false
    post: false
    book: false
show_related:
  book: true
  page: true
  post: true
  project: true
  publication: true
  event: true
reading_time: true
section_pager: true
docs_section_pager: true
sharing: true
copyright_license:
  enable: false
  allow_derivatives: false
  share_alike: true
  allow_commercial: false
  notice: 'Tulisan ini berlisensi {license}'
abstract_length: 135
plugins_js: []
avatar:
  gravatar: false
  shape: circle
publications:
  date_format: January 2006
  citation_style: apa
projects:
  post_view: 2
  publication_view: 2
  talk_view: 2
breadcrumb:
  page_types:
    book: true
comments:
  provider: ''
  commentable:
    post: true
    book: true
    project: true
    publication: true
    event: true
  disqus:
    shortname: ''
    show_count: true
  commento:
    url: ''
search:
  provider: wowchemy
  algolia:
    app_id: ''
    api_key: ''
    index_name: ''
    show_logo: false
map:
  provider: mapnik
  api_key: ''
  zoom: 15
marketing:
  google_analytics: ''
  google_tag_manager: ''
  google_site_verification: ''
  baidu_site_verification: ''
  baidu_tongji: ''
cms:
  branch: master
  local_backend: false
icon:
  pack:
    ai: true
